admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

invoice:
    resource: "@InvoiceBundle/Resources/config/routing.yml"
    prefix:   /invoice

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

card:
    resource: "@CardBundle/Resources/config/routing.yml"
    prefix:   /card

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /