# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    cards_processor:
        class: ImportBundle\Processor\CardsProcessor
        arguments: ['@service_container']
    users_processor:
        class: ImportBundle\Processor\UsersProcessor
        arguments: ['@service_container']
    api_controller:
        class: ApiBundle\ApiController
        arguments: ['@service_container']
