app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:home }

logout:
    path:    /logout
    defaults: { _controller: AppBundle:App:logout }

check_card_validity:
    path:   /check_card_validity/{cardNumber}
    defaults: { _controller: AppBundle:App:checkCardValidity }